// Package tsgen writes the TypeScript types of the views the core sends
// (docs/adr/0039-presentation-split.md), from the very Go types that encode
// them, so the web client's types cannot drift from the contract: the file is
// generated, checked in under api/, and a test fails when the Go views change
// without it being regenerated.
package tsgen

import (
	"fmt"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/mrjvadi/torncity/internal/presentation"
)

var (
	durationType = reflect.TypeOf(time.Duration(0))
	timeType     = reflect.TypeOf(time.Time{})
)

// Generate returns the TypeScript declarations of every defined screen's view
// and the ScreenViews map from a screen's name to its view type.
func Generate(specs []presentation.Spec) string {
	g := &gen{decls: map[string]string{}, types: map[string]reflect.Type{}, order: nil}
	for _, s := range specs {
		g.ref(s.View)
	}
	var b strings.Builder
	b.WriteString("// GENERATED by cmd/contractgen from the Go view types (docs/adr/0039-presentation-split.md).\n")
	b.WriteString("// Do not edit: change the Go view, run `go run ./cmd/contractgen > api/views.gen.ts`.\n")
	b.WriteString("//\n")
	b.WriteString("// Every field is always present. A nil pointer, slice or map, and a zero time, are null.\n")
	b.WriteString("// A duration is whole seconds, rounded up, under the field's name with `_seconds` appended.\n\n")
	names := append([]string(nil), g.order...)
	sort.Strings(names)
	for _, n := range names {
		b.WriteString(g.decls[n])
		b.WriteString("\n")
	}
	b.WriteString("/** The screens of the migrated areas: the screen name on the wire, and its view. */\n")
	b.WriteString("export interface ScreenViews {\n")
	for _, s := range specs {
		fmt.Fprintf(&b, "  %s: %s\n", s.Name, g.ref(s.View))
	}
	b.WriteString("}\n\n")
	b.WriteString("/** Screens whose response is a refusal: the answer carries an error code instead of ok. */\n")
	b.WriteString("export const REFUSAL_SCREENS = [")
	var refusals []string
	for _, s := range specs {
		if s.Refusal {
			refusals = append(refusals, fmt.Sprintf("'%s'", s.Name))
		}
	}
	b.WriteString(strings.Join(refusals, ", "))
	b.WriteString("] as const\n")
	return b.String()
}

// Collisions lists the type names two different Go structs share. The file is flat
// by name, so the second struct would silently take the first one's declaration
// (a village shop's view drawn as a city shop's): every name must be one struct.
func Collisions(specs []presentation.Spec) []string {
	g := &gen{decls: map[string]string{}, types: map[string]reflect.Type{}}
	for _, s := range specs {
		g.ref(s.View)
	}
	sort.Strings(g.clash)
	return g.clash
}

type gen struct {
	decls map[string]string
	// types remembers which Go struct a name was declared from, so a second
	// struct of the same name is found rather than merged.
	types map[string]reflect.Type
	order []string
	clash []string
}

// ref returns the TypeScript spelling of a type, declaring named structs as
// it meets them.
func (g *gen) ref(t reflect.Type) string {
	switch t {
	case durationType:
		return "number"
	case timeType:
		return "string | null"
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Pointer:
		return g.ref(t.Elem()) + " | null"
	case reflect.Slice:
		return wrap(g.ref(t.Elem())) + "[] | null"
	case reflect.Array:
		return wrap(g.ref(t.Elem())) + "[]"
	case reflect.Map:
		return "Record<string, " + g.ref(t.Elem()) + "> | null"
	case reflect.Struct:
		if t.Name() == "" {
			return g.body(t)
		}
		name := t.Name()
		if prev, ok := g.types[name]; !ok {
			g.types[name] = t
		} else if prev != t && shape(prev) != shape(t) {
			g.clash = append(g.clash, fmt.Sprintf("%s: %s and %s", name, prev, t))
		}
		if _, ok := g.decls[name]; !ok {
			g.decls[name] = "" // reserve: a struct may mention itself
			g.order = append(g.order, name)
			g.decls[name] = fmt.Sprintf("export interface %s %s\n", name, g.body(t))
		}
		return name
	}
	return "unknown"
}

// shape is a struct's fields by wire key and Go type, so two structs of one name
// that mean the same thing (a reference copied between packages) are not a clash.
func shape(t reflect.Type) string {
	var b strings.Builder
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if key, ok := presentation.FieldKey(f); ok {
			b.WriteString(key + ":" + f.Type.Name() + f.Type.Kind().String() + ";")
		}
	}
	return b.String()
}

func wrap(s string) string {
	if strings.Contains(s, " | ") {
		return "(" + s + ")"
	}
	return s
}

// body is a struct's fields, in the keys and shapes the view encoding writes.
func (g *gen) body(t reflect.Type) string {
	var b strings.Builder
	b.WriteString("{\n")
	g.fields(&b, t)
	b.WriteString("}")
	return b.String()
}

func (g *gen) fields(b *strings.Builder, t reflect.Type) {
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.Anonymous && f.Type.Kind() == reflect.Struct && f.Type != timeType {
			g.fields(b, f.Type)
			continue
		}
		key, ok := presentation.FieldKey(f)
		if !ok {
			continue
		}
		typ := g.ref(f.Type)
		if f.Type.Kind() == reflect.Interface || f.Type.String() == "json.RawMessage" {
			typ = "unknown"
		}
		fmt.Fprintf(b, "  %s: %s\n", key, typ)
	}
}
